services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  codeexecutionservice:
    build:
      context: ./CodeExecutionService
      dockerfile: Dockerfile
    ports:
      - "20001:8080" 
    environment:
      RabbitMQ:HostName: rabbitmq 
      RabbitMQ:RequestQueue: code_execution_requests
      RabbitMQ:ResultQueue: code_execution_results
    depends_on:
      rabbitmq:
        condition: service_healthy 

  codeexecutionworker:
    build:
      context: ./CodeExecutionWorker
      dockerfile: Dockerfile
    environment:
      RabbitMQ:HostName: rabbitmq 
      RabbitMQ:RequestQueue: code_execution_requests
      RabbitMQ:ResultQueue: code_execution_results
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock